version: '3.8'

services:
  app:
    build: .
    ports:
      - "4235:4235"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs 