version: '3.8'

services:
  homeland:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - NODE_ENV=production
        - PORT=4235
        - HOSTNAME=0.0.0.0
    container_name: homeland-app
    # 使用 host 网络模式，容器直接使用宿主机网络
    network_mode: host
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - PORT=4235
      - HOSTNAME=0.0.0.0
    restart: unless-stopped

networks:
  homeland-network:
    driver: bridge 